소프트맥스 비용

In [17]:
import torch
import torch.nn.functional as F

torch.manual_seed(1)

1,2,3이라는 숫자로 softmax를 취함.

In [18]:
z=torch.FloatTensor([1,2,3])
h=F.softmax(z, dim=0)

print(h)
h.sum()


tensor([0.0900, 0.2447, 0.6652])


tensor(1.)

In [19]:
z=torch.rand(3,5, requires_grad=True)
print(z)
h=F.softmax(z, dim=1)
print(h)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)
tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


랜덤하게 정수를 만들어보자. 5보다 작은 정수, 0-4까지 의 정수를 3개 long 형으로 만들어
10까지 하고 정수 5개 (10, (5,))
원핫 인코딩하려고 만들었어.

In [20]:
y=torch.randint(5,(3,)).long()
print(y)

tensor([0, 2, 1])


3행 5열짜리 배열이 필요한데, 전체 0, tensur로

원핫인코딩해보자.
y는 1차원 상태

In [21]:
y_one_hot=torch.zeros_like(h)
print(y_one_hot)
print(y.unsqueeze(1)) #1에다가 차원을 높힐때 이걸 쓴다. 2차원은 인덱스 0, 1차원은 인덱스 1

y_one_hot.scatter_(1, y.unsqueeze(1),1) # 1 위치에 scatter 1을 그려라 () 1=이건 행)
print(y_one_hot)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0],
        [2],
        [1]])
tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])


손실함수를 구하자.
원래의 값과 softmax의 값을..? ㅇㅁㅇ 와우 못알아들었다.

In [22]:
cost=(y_one_hot* -torch.log(h)).sum(dim=1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


row로 잘 안쓴다. 아무도 안쓴다!!
하이레벨로 쓴데.


하이_레벨

In [23]:
# Low level
torch.log(F.softmax(z, dim=1))
# High level
F.log_softmax(z, dim=1)
# Low level
# 첫번째수식
(y_one_hot* -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()
# 두번째수식
(y_one_hot* -F.log_softmax(z, dim=1)).sum(dim=1).mean()

# High level
# 세번째수식
F.nll_loss(F.log_softmax(z, dim=1), y)
# 네번째수식
F.cross_entropy(z, y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

사실 하이레벨도 안한다. 그냥 소프트 엔트로피 한데?


In [24]:
F.nll_loss(F.log_softmax(z, dim=1), y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

그냥 이거 바로쓴데. 그러면 앞에 값을 세팅하고 이렇게 쓰는건가?

In [25]:
F.cross_entropy(z,y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

실습: mnist 데이터 셋
0~9까지 여러개 저장을 해두고, 넣으면 1번 2번 답이 나오는지
이미지에 정답을 다 달아놨어.
