파이토치가 설치되었는지 확인해야해.

In [ ]:
# ! pip install torch

   ---------------------------------------- 0.0/110.9 MB ? eta -:--:--
   ----- ---------------------------------- 15.5/110.9 MB 79.2 MB/s eta 0:00:02
   ----------- ---------------------------- 31.7/110.9 MB 76.7 MB/s eta 0:00:02
   ------------ --------------------------- 35.7/110.9 MB 57.9 MB/s eta 0:00:02
   ------------------ --------------------- 52.2/110.9 MB 63.7 MB/s eta 0:00:01
   --------------------- ------------------ 58.5/110.9 MB 57.1 MB/s eta 0:00:01
   ----------------------- ---------------- 64.5/110.9 MB 52.4 MB/s eta 0:00:01
   ---------------------------- ----------- 80.0/110.9 MB 55.8 MB/s eta 0:00:01
   --------------------------------- ------ 93.3/110.9 MB 58.3 MB/s eta 0:00:01
   ---------------------------------- ----- 94.9/110.9 MB 51.5 MB/s eta 0:00:01
   ----------------------------------- ---- 99.1/110.9 MB 48.5 MB/s eta 0:00:01
   --------------------------------------  110.9/110.9 MB 50.6 MB/s eta 0:00:01
   --------------------------------------  110.9/

In [3]:
import torch

텐서만들기
변수 = torch.tensor([])

정수형 텐서

In [4]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

실수형 텐서

In [5]:
b=torch.tensor([0.1, 2.5, 3.6])
b

tensor([0.1000, 2.5000, 3.6000])

2차원 텐서

In [6]:
c=torch.tensor([[1,2],[3,4]])
c

tensor([[1, 2],
        [3, 4]])

형 지정 가능 - 데이터를 직접 입력
정수를 넣었지만 실수형으로 만들 수 있어.


In [7]:
ft=torch.FloatTensor([1,2,3])
ft

tensor([1., 2., 3.])

In [8]:
lt=torch.LongTensor([1,2,3])
lt

tensor([1, 2, 3])

In [9]:
bt=torch.ByteTensor([1,2,3])
bt

tensor([1, 2, 3], dtype=torch.uint8)

--------작성 형태---------

In [10]:
d=torch.tensor([1,2,3],dtype=torch.float64)
d

tensor([1., 2., 3.], dtype=torch.float64)

dtype 쓰는게 귀찮으니까 아래 같이 쓰는게 편해.

In [11]:
bt=torch.ByteTensor([1,2,3])
bt

tensor([1, 2, 3], dtype=torch.uint8)

GPU를 쓸대 cuda를 사용함. 아래와 같이 사용하면 됨.

In [ ]:
# d=torch.tensor([1,2,3],dtype=torch.float64, device='cuda:0')
# d

AssertionError: Torch not compiled with CUDA enabled

텐서는 넘파이와 호환이 됨.

In [14]:
import numpy as np
x=np.array([[1,2], [3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


numpy 배열을 토치로 만든다.

In [16]:
x1=torch.from_numpy(x)
print(x1, type(x1))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


토치를 넘파이로 바꿔보자.

In [17]:
x2=x1.numpy()
print(x2, type(x2))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


형 변환
실수형 텐스를 <-> long 

In [21]:
print(ft)
print(ft.long())
print(ft.float())
print(ft.byte())

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


In [25]:
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6], [7,8]],[[9,10],[11,12]]])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

텐서 크기 보기

In [ ]:
x.size()


torch.Size([3, 2, 2])

In [ ]:
print(x.size())
print(x.shape) #넘파이 명령어도 잘 먹혀

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


size의 순서
차원의 크기를 인덱스로 잡아. size는 ()

In [ ]:
print(x.size(1))
print(x.size(0))
print(x.size(2))
print(x.size(-1))

2
3
2
2


shape를 할때는 배열처럼, [] 사용해.

In [56]:
print(x.shape[0])
print(x.shape[1])
print(x.shape[2])
print(x.shape[-1])

3
2
2
2


x가 몇차원인지 알려주는 dim

In [57]:
print(x.dim())
print(len(x.shape)) # numpy 배열에서 차원의 수 구하기

3
3


텐서의 기본 연산
+, -, * , /, ==, !=, **(지수연산)

In [58]:
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])

print(a, b)

tensor([[1., 2.],
        [3., 4.]]) tensor([[2., 2.],
        [3., 3.]])


요소와 요소끼리 계산된거라서 요소가 안맞으면 계산이 안됨.

In [59]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b) #정수의 몫만 남겨
print('=================')
print(a==b)
print(a!=b)
print(a**b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[0., 1.],
        [1., 1.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 64.]])


연산을 해도 값이 변하지 않아

In [60]:
print(a)
print(a.mul(b)) #a*b
print(a.add(b)) #a+b
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[3., 4.],
        [6., 7.]])
tensor([[1., 2.],
        [3., 4.]])


언더바하면 a=a+b 해줘라. / 언더바 없으면 a+b

In [61]:
print(a)
print(a.add_(b)) #a+b
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[3., 4.],
        [6., 7.]])
tensor([[3., 4.],
        [6., 7.]])


In [ ]:
print(a)
print(a.sum())
print(a.mean())
print(a.sum(dim=0)) # 열별로 더하고 - 세로로
print(a.sum(dim=1)) # 행별로 더하고 - 가로로

tensor([[3., 4.],
        [6., 7.]])
tensor(20.)
tensor(5.)
tensor([ 9., 11.])
tensor([ 7., 13.])


In [63]:
x=torch.FloatTensor([[1,2,3], [4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

요소가 같으니까 이렇게 계산이 잘 되었는데...
요소가 다르거나, 차원이 다른 경우 어떻게 되는 걸까?

x라는 텐서에 스칼라(숫자1개) 더하기(각각 요소에 1을 더해)

In [64]:
print(x+1)

tensor([[2., 3., 4.],
        [5., 6., 7.]])


1차원을 더해보자


In [71]:
y1=torch.FloatTensor([1,2,3])
print(x)
print(x+y1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[2., 4., 6.],
        [5., 7., 9.]])


브로드캐스트 연산, 서로 차원이 다른 연산끼리 합산할때 어떻게 맞출 것인가.
1차원의 크기가 2차원의 1차원 요소크기가 맞아야해. 아래는 에러나

In [ ]:
# y1=torch.FloatTensor([1,2,3,4])
# print(x+y1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

차원이 작은 텐서의 갯수와 차원이 큰 부분의 텐서 작은 부분이 같아야해.
2차원의 크기와 3차원의 2차원 작은 부분이 맞아야해.

In [ ]:
y2=torch.FloatTensor([[[1,2,3],[1,2,3]],[[7,5,6],[4,5,6]]])
print(y2.size())
print(x.size())
print(x)
print(x+y2)

torch.Size([2, 2, 3])
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[ 2.,  4.,  6.],
         [ 5.,  7.,  9.]],

        [[ 8.,  7.,  9.],
         [ 8., 10., 12.]]])


크기가 안돼.
2차원과 1차원 맞는 부분이 있어야지 연산이 돼.


In [ ]:
# y2=torch.FloatTensor([[[1,2,3,1],[1,2,3,2]],[[7,5,6,2],[4,5,6,2]]])
print(y2.size())
print(x.size())
print(x)
print(x+y2)

torch.Size([2, 2, 4])
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 2

1차원 텐서를 만들어

In [ ]:
x=torch.FloatTensor([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  9., 10., 12.])


In [75]:
x=torch.FloatTensor([1,2,3,4,5,6,7,8,9,10,11,12])
x1=x.view(3,4)
print(x)
print(x1)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


3차원

In [78]:
x=torch.FloatTensor([1,2,3,4,5,6,7,8,9,10,11,12])
x1=x.view(3,4)
x2=x.view(3,2,-1) # -1을 앞이든 뒤든 넣어서 맞는 수를 찾아서 넣는데???
print(x)
print(x1)
print(x2)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


뷰는 차원을 고치는 것.
reshape를 해도 똑같아.

In [79]:
y1=x.reshape(3,4)
print(y1)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [80]:
y1=x.reshape(3,-1)
print(y1)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


arange 숫자 넣어도 됨

In [ ]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
x=torch.from_numpy(a)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

선생님 교재 따라하기

In [90]:
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [91]:
print(x.view(3,4))
print(x.reshape(3,4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [93]:
print(x.view(3,1,4))
print(x.reshape(3,1,4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


텐서의 형태 변환

In [99]:
a=np.arange(12)
x=torch.from_numpy(a)
x
x1=x.view(3,-1,4)
x1

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

squeezz를 싸면 1인 차원을 제거해줘

In [ ]:
print(x1.size())
x2=x1.squeeze()
print(x2)
print(x1.size(), x2.size()) # x1은 1차원이 3, 2차원이 1, 3차원이 4, x2는 1차원 없앰

torch.Size([3, 1, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 1, 4]) torch.Size([3, 4])


1차원을 만들어줘
unsqueeze는 차원의 순서(1)
내가 어느차원에 크기가 1인 차원에 들어갈건가. 0, 1,2 1을 넣으니까 2차원 위치로 들어가.
size의 순서번호

In [ ]:
x3=x2.unsqueeze(1) #0,1,2
print(x3.size())

torch.Size([3, 1, 4])


머신러닝할때 연산을 하는데 차원이 맞춰져야지 계산이 가능해.

인덱싱과 슬라이싱 /2차원 x2 소환

In [116]:
x2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

[1][2]1차원, 2차원
인덱스 고르기

In [106]:
x2[1][2]

tensor(6)

모든행 모든열

In [107]:
x2[:,:]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

스텝을 줄수도 있어

IndexError: too many indices for tensor of dimension 2

In [ ]:
x2[:2,:]

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [114]:
x2[:2,:-1] #맨 마지막 앞까지

tensor([[0, 1, 2],
        [4, 5, 6]])

In [118]:
indice = torch.LongTensor([2,1])

2차원이니까  dim 0은 2차원이다.

In [119]:
print(x2)
x4=x2.index_select(dim=0, index=indice)
print(x4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 8,  9, 10, 11],
        [ 4,  5,  6,  7]])


In [120]:
print(x2)
x4=x2.index_select(dim=1, index=indice)
print(x4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  1],
        [ 6,  5],
        [10,  9]])


선생님 자료

In [121]:
x = torch.FloatTensor([[[1, 2],
[3, 4]],
[[5, 6],
[7, 8]],
[[9, 10],
[11, 12]]])
print(x.size()) 

torch.Size([3, 2, 2])


In [123]:
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [124]:
print(x[0,:])

tensor([[1., 2.],
        [3., 4.]])


In [125]:
print(x[0,:,:])

tensor([[1., 2.],
        [3., 4.]])


텐서가 많이 크면 자르고 붙이기 가능

In [126]:
x=torch.FloatTensor(10,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

dim0 니까 첫번째 차원? , 2차원이 4개로 잘린다?
10행 4열인데 행으로 4열을 나눠

테스트와 훈련데이터를 잘라서 분석하면 됨.

In [132]:
x=torch.FloatTensor(10,4)
x1=x.split(4, dim=0)
for xi in x1:
  print(xi.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


chunk 파이썬에서 기록하는 단위

In [133]:
x = torch.FloatTensor(10,4)
x2=x.chunk(3, dim=0)

for c in x2:
  print(c.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


index로 일부분 가지고 올수 잇어.
index_select

In [134]:
x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                        [[3, 3],
                        [4, 4]],
                        [[5, 5],
                        [6, 6]]])
indice= torch.LongTensor([2, 1])
print(x.size())

torch.Size([3, 2, 2])


In [135]:
y = x.index_select(dim=0, index=indice)
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


concatenate 함수는 붙히는 것

In [136]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]])
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


3차원이면 dim=0 으로 했을때 3차원으로 작업될거야.

In [137]:
z = torch.cat([x, y], dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [138]:
z = torch.cat([x, y], dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


stack => 2차원을 3차원으로 쌓아. dim을 줄수있데?

In [139]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]])

In [140]:
z = torch.stack([x, y])
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


-1은, 끝에 2가 되는????????
3차원 2차원 ???
stack은 차원이 증가시키고, 차원의 정보를 쓰지 않으면 제일 높은 차원이 증가.
차원을 써주면 원래데이터를 유지하면서 모양이 바껴

1을 쓰면 2차원 1부분이, -1이나 2 쓰며 1차원 부분이 

In [141]:
z = torch.stack([x, y], dim=-1)
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


유용한 함수!!!!!!!!!!!!!!!!!

Random Pernutation 

2차원a

In [143]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [144]:
a=np.arange(9).reshape(3,3)
x=torch.from_numpy(a)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

2차원 크기가 1됨. expand를 쓰면
2차원을 1 넣어서 3차원 텐서로 바꿨어.

In [147]:
x1=x.view(3,1,3)
x1

tensor([[[0, 1, 2]],

        [[3, 4, 5]],

        [[6, 7, 8]]])

2차원 똑같은 것을 복사해. 
크기가 1인 곳을 알아야지 이렇게 한데. 무슨말이지?

In [149]:
y=x1.expand(3,2,3)
y

tensor([[[0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5]],

        [[6, 7, 8],
         [6, 7, 8]]])

In [150]:
y=x1.expand(3,3,3)
y

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5],
         [3, 4, 5]],

        [[6, 7, 8],
         [6, 7, 8],
         [6, 7, 8]]])

데이터 섞을때 많이 쓰는 함수
Random Pernutation 함수

In [151]:
x=torch.randperm(10)
print(x)
print(x.size())

tensor([0, 5, 1, 9, 4, 8, 2, 7, 6, 3])
torch.Size([10])


In [152]:
x=torch.randperm(3**3).reshape(3,3,-1)
print(x)
print(x.size())

tensor([[[17, 14, 11],
         [19, 16,  4],
         [21,  9,  5]],

        [[15,  8, 23],
         [20, 25, 22],
         [13,  2,  3]],

        [[10, 12, 26],
         [ 7, 18,  1],
         [24,  0,  6]]])
torch.Size([3, 3, 3])


행에서 제일 큰 값을 찾아.
ex. 개와 고양이를 찾을 때 몇 %인지 퍼센트로 확인 됨. 이 것은 뭐 입니다. 하고 설명을 달아야하는데 분류알고리즘을 하면 뭐일 확률 몇퍼센트, 가장 큰 값으로 이건 뭐다! 표현해야하니까. 많이써.

어느차원에서 가장 큰 값인가

In [153]:
x=torch.randperm(3**3).view(3,3,-1)
x

tensor([[[ 5,  7,  8],
         [ 9,  0, 22],
         [23, 16,  4]],

        [[14, 25, 11],
         [15, 17,  2],
         [12, 10, 13]],

        [[ 3, 19,  6],
         [26, 24,  1],
         [21, 18, 20]]])

행으로 비교해서 제일 큰 값 각각
이게 제일 많이 쓰여!!!

In [156]:
y1=x.argmax(dim=-1)
y1

tensor([[2, 2, 0],
        [1, 1, 2],
        [1, 0, 0]])

열로 비교해서 제일 큰 값

In [159]:
y2=x.argmax(dim=1)
y2

tensor([[2, 2, 1],
        [1, 0, 2],
        [1, 1, 2]])

3차원

In [160]:
y3=x.argmax(dim=0)
y3

tensor([[1, 1, 1],
        [2, 2, 0],
        [0, 2, 2]])

조금전까지는 위치를 찾은 것.
Top-k 가장 큰 k개 값과 index를 찾아줘.
각 행에서 제일 큰 값을 찾아줘.

In [161]:
values, indes=torch.topk(x, k=1, dim=-1)
print(values)
print(indes)
print(values.size())
print(indes.size())

tensor([[[ 8],
         [22],
         [23]],

        [[25],
         [17],
         [13]],

        [[19],
         [26],
         [21]]])
tensor([[[2],
         [2],
         [0]],

        [[1],
         [1],
         [2]],

        [[1],
         [0],
         [0]]])
torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


k=2 하면 큰거 2개를 찾아.
dim=-1 이걸 조절하면 차원 요소에서 찾을 수 있어.

In [162]:
values, indes=torch.topk(x, k=2, dim=-1)
print(values)
print(indes)
print(values.size())
print(indes.size())

tensor([[[ 8,  7],
         [22,  9],
         [23, 16]],

        [[25, 14],
         [17, 15],
         [13, 12]],

        [[19,  6],
         [26, 24],
         [21, 20]]])
tensor([[[2, 1],
         [2, 0],
         [0, 1]],

        [[1, 0],
         [1, 0],
         [2, 0]],

        [[1, 2],
         [0, 1],
         [0, 2]]])
torch.Size([3, 3, 2])
torch.Size([3, 3, 2])


Masked Fill


In [ ]:
x=torch.FloatTensor([i for i in range(3**2)]).view(3,-1)
x
print(x)
print(x>4)
mask=x>4
mask
y=x.masked_fill(mask, value=-100) #마스크 채워진 곳에 -100을 채워라. 0 넣어도 0. 값을 적용만 하는 것.
print(y)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[   0.,    1.,    2.],
        [   3.,    4., -100.],
        [-100., -100., -100.]])


ones
파이썬에서는 한줄에 명령이 2개 이상일때는 ; 으로 구분함.
2행 3열에 1, zeros

In [ ]:
a=np.ones([2,3]) #2개 이상의 값을 주면 [] 싸줘야해
print(a)
b=np.zeros([2,3])
print(b)
c=np.ones_like(x) # x라는 배열 크기만큼 1을 채우겠다.
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [175]:
print(torch.ones(2,3))
print(torch.zeros(2,3))

x=torch.FloatTensor([[1,2,3], [4,5,6]])
print(x)
print(x.size())

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
