In [107]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

seed 값 줘야지 돌릴때마다 랜덤 w, b 값이 변형이 없다.

5행 1열로 만들자.

In [108]:
torch.manual_seed(0)
x_train = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
y_train = torch.tensor([[3.0], [5.0], [7.0], [9.0], [11.0]])
print(x_train.size())
print(y_train.size())

torch.Size([5, 1])
torch.Size([5, 1])


In [109]:
W=torch.zeros(1, requires_grad=True)
b=torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


수식 만들기

랜덤하게 만든게 아니고 0값을 줬으니까 아래의 결과가 나옴.

In [110]:
y=x_train*W+b
print('y=',y)

y= tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


cost 함수 만들기

y_train = torch.tensor([[3.0], [5.0], [7.0], [9.0], [11.0]]) 제곱한걸 다 더해서 평균 낸 것
손실함수야.

In [111]:
cost=torch.mean((y-y_train)**2)
print(cost)

tensor(57., grad_fn=<MeanBackward0>)


최적화 하자

In [112]:
optimizer = optim.SGD([W,b], lr=0.01) #e-2과 같아
epochs=2001

2x+1 의 식을 갖어.
지금은 우리가 입력 값이 작아서 베치사이즈를 안준거야.
베치사이를 준다면 for문으로 써. 100을 준다면

In [113]:
for epoch in range(epochs):
  #베치사이즈 만큼 x데이터 y데이터 만큼 불러서 아래의 optimizer ~ 부터 한번 하고 그 아래에 하나씩 하는 것
  # 1에폭이 100만개, 배치가 100개면 1만번 돌면 1에폭

  optimizer.zero_grad() #한번 돌면 optim 값이 생기니까 클리어

  y= x_train*W + b #가상의 값 만들기
  cost=torch.mean((y-y_train)**2) #제곱한거의 평균 , 한에폭의 전체값의 평균의 2승?? 2차원 배열로 1에폭?
  cost.backward() #최적화하려면 기울기를 그려야해. 딥러닝같으면 앞 단계 손실함수도 전파하는 역할???
  optimizer.step() #w와 b를 업데이트

  if epoch %10==0:
    print(f'Epoch{epoch},Loss:{cost.item()}, w:{W.item()}, b:{b.item()}') #cost.item()텐서속의 숫자를 꺼낸다는 뜻


Epoch0,Loss:57.0, w:0.5, b:0.14000000059604645
Epoch10,Loss:0.28650277853012085, w:2.002049446105957, b:0.5708461999893188
Epoch20,Loss:0.02843988500535488, w:2.099571943283081, b:0.6121681332588196
Epoch30,Loss:0.0254964642226696, w:2.1028151512145996, b:0.6268995404243469
Epoch40,Loss:0.023821769282221794, w:2.09983229637146, b:0.6394458413124084
Epoch50,Loss:0.02226170152425766, w:2.0965375900268555, b:0.6514604091644287
Epoch60,Loss:0.020803730934858322, w:2.093324661254883, b:0.6630672216415405
Epoch70,Loss:0.01944129168987274, w:2.090217113494873, b:0.6742870807647705
Epoch80,Loss:0.01816803589463234, w:2.0872130393981934, b:0.6851333975791931
Epoch90,Loss:0.016978196799755096, w:2.084308624267578, b:0.6956184506416321
Epoch100,Loss:0.01586623676121235, w:2.0815012454986572, b:0.7057543396949768
Epoch110,Loss:0.01482720859348774, w:2.078787326812744, b:0.7155526876449585
Epoch120,Loss:0.013856078498065472, w:2.0761637687683105, b:0.7250247597694397
Epoch130,Loss:0.012948649935424

optimizer.zero_grad()가 필요한 이유는 이전 값이 계속 나와.
이전 값을 가지고 계속 미분을 해. 한 에폭마다, 한 베치마다 깨끗히 만들고 작업해.

In [114]:
w = torch.tensor(2.0, requires_grad=True)
print(w)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  z = 2*w
  z.backward()
  print('수식을 w로미분한값: {}'.format(w.grad))

tensor(2., requires_grad=True)
수식을 w로미분한값: 2.0
수식을 w로미분한값: 4.0
수식을 w로미분한값: 6.0
수식을 w로미분한값: 8.0
수식을 w로미분한값: 10.0
수식을 w로미분한값: 12.0
수식을 w로미분한값: 14.0
수식을 w로미분한값: 16.0
수식을 w로미분한값: 18.0
수식을 w로미분한값: 20.0
수식을 w로미분한값: 22.0
수식을 w로미분한값: 24.0
수식을 w로미분한값: 26.0
수식을 w로미분한값: 28.0
수식을 w로미분한값: 30.0
수식을 w로미분한값: 32.0
수식을 w로미분한값: 34.0
수식을 w로미분한값: 36.0
수식을 w로미분한값: 38.0
수식을 w로미분한값: 40.0
수식을 w로미분한값: 42.0


torch.manual_seed()를하는 이유는 랜덤 함수 할 때 계속 같은 값이 나와.
seed 수는 관례적으로 0을 넣을 때도 있고, 42를 넣을 때도 있어. 어떤 값을 넣어도 상관없고 [고정했다]가 중요.

In [115]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1,3):
    print(torch.rand(1))


랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


자동 미분!!!!!!!!!!!!!!
2w**2 + 5 자동 미분하기

In [116]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y+5

z.backward() #기울기 계산

print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


파일을 그대로 불러와서 작업해보자. 판다스 추가!!

In [117]:
import pandas as pd
import numpy as np

In [131]:
df=pd.read_csv('../data02/data-01-test-score.csv')
df

73  80   75  152
0   93  88   93  185
1   89  91   90  180
2   96  98  100  196
3   73  66   70  142
4   53  46   55  101
5   69  74   77  149
6   47  56   60  115
7   87  79   90  175
8   79  70   88  164
9   69  70   73  141
10  70  65   74  141
11  93  95   91  184
12  79  80   73  152
13  70  73   78  148
14  93  89   96  192
15  78  75   68  147
16  81  90   93  183
17  88  92   86  177
18  78  83   77  159
19  82  86   90  177
20  86  82   89  175
21  78  83   85  175
22  76  83   71  149
23  96  93   95  192

df.values는 넘파이 2차원 배열이야.
행은 학생(데이터 갯수) 열은 4개이고 (과목 3 + 목표값 1)이야.
형태로 따지면 shape(24,4)의 꼴이야.

배열로 만들어보자!!!!!!!!!!!!!!!!!!!!!!!!!

In [119]:
x_data=df.values[:, :-1]
x_data

array([[ 93,  88,  93],
       [ 89,  91,  90],
       [ 96,  98, 100],
       [ 73,  66,  70],
       [ 53,  46,  55],
       [ 69,  74,  77],
       [ 47,  56,  60],
       [ 87,  79,  90],
       [ 79,  70,  88],
       [ 69,  70,  73],
       [ 70,  65,  74],
       [ 93,  95,  91],
       [ 79,  80,  73],
       [ 70,  73,  78],
       [ 93,  89,  96],
       [ 78,  75,  68],
       [ 81,  90,  93],
       [ 88,  92,  86],
       [ 78,  83,  77],
       [ 82,  86,  90],
       [ 86,  82,  89],
       [ 78,  83,  85],
       [ 76,  83,  71],
       [ 96,  93,  95]])

:-1 은 마지막 열 빼고 전부라는 뜻이야.
형태로 따지면 x_data shape(24,3)의 꼴이야.
즉, 입력변수가 3짜리야.

y1 = df.values[:, -1]
이 결과는 1차원이 됨.
shape(24,) 24짜리 벡터임.
넘파이에서는 이런 건 행렬이 아니라 벡터(1D)로 취급이 됨.

대괄호 2개사용: 여기서 [-1]이 리스트라서 넘파이가 열을 1개 선택하되, 2차원 형태를 유지해줘라고 명령
shape(24,1) 열이 1개짜리 2차원 행렬 (24,1)이 됨.

In [120]:
#연습
A=np.arange(12).reshape(3,4)
print(A)
A1=A[:,-1]
print(A1) #shape(3,)
A2=A[:,[-1]]
print(A2) #shape(3,1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11]
[[ 3]
 [ 7]
 [11]]


In [121]:
y_data=df.values[:, [-1]] #1차원 안되게 [] 했다는데 머선말이지
y_data

array([[185],
       [180],
       [196],
       [142],
       [101],
       [149],
       [115],
       [175],
       [164],
       [141],
       [141],
       [184],
       [152],
       [148],
       [192],
       [147],
       [183],
       [177],
       [159],
       [177],
       [175],
       [175],
       [149],
       [192]])

텐서로 바꿔보자.
근데 이걸 왜 텐서로 바꾸는지 잘 모르겠어..

In [122]:
xdata=torch.from_numpy(x_data)
ydata=torch.from_numpy(y_data)
print(xdata)
print(ydata)

tensor([[ 93,  88,  93],
        [ 89,  91,  90],
        [ 96,  98, 100],
        [ 73,  66,  70],
        [ 53,  46,  55],
        [ 69,  74,  77],
        [ 47,  56,  60],
        [ 87,  79,  90],
        [ 79,  70,  88],
        [ 69,  70,  73],
        [ 70,  65,  74],
        [ 93,  95,  91],
        [ 79,  80,  73],
        [ 70,  73,  78],
        [ 93,  89,  96],
        [ 78,  75,  68],
        [ 81,  90,  93],
        [ 88,  92,  86],
        [ 78,  83,  77],
        [ 82,  86,  90],
        [ 86,  82,  89],
        [ 78,  83,  85],
        [ 76,  83,  71],
        [ 96,  93,  95]])
tensor([[185],
        [180],
        [196],
        [142],
        [101],
        [149],
        [115],
        [175],
        [164],
        [141],
        [141],
        [184],
        [152],
        [148],
        [192],
        [147],
        [183],
        [177],
        [159],
        [177],
        [175],
        [175],
        [149],
        [192]])


정수로 되어있으니까 float 실수로 바꿔보자.

In [123]:
xdata=torch.from_numpy(x_data).float()
ydata=torch.from_numpy(y_data).float()
print(xdata)
print(ydata)

tensor([[ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  93.],
        [ 88.,  92.,  86.],
        [ 78.,  83.,  77.],
        [ 82.,  86.,  90.],
        [ 86.,  82.,  89.],
        [ 78.,  83.,  85.],
        [ 76.,  83.,  71.],
        [ 96.,  93.,  95.]])
tensor([[185.],
        [180.],
        [196.],
        [142.],
        [101.],
        [149.],
        [115.],
        [175.],
        [164.],
        [141.],
        [141.],
        [184.],
        [152.],
        [148.],
        [192.],
        [147.],
        [183.],
        [177.],
        [159.],
        [177.],
       

w를 3행 1열로 만들어야해.

In [124]:
W=torch.zeros((3,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [125]:
optimizer=optim.SGD([W,b], lr=0.0001) #10**-4 정도
epochs=20001


loss 값이 많이 안줄면 멈춰도 된다. 더 할 필요는 없어.

In [126]:
for epoch in range(epochs):
  optimizer.zero_grad()
  y=xdata.matmul(W)+b #배열의 곱이라서 matmul 사용을 해야해 아니면 dot 하던가!!!!!!!!!!!
  cost=torch.mean((y-ydata)**2)
  cost.backward()
  optimizer.step()

  if epoch %100 ==0:
    print(f'Epoch:{epoch}, Loss:{cost}, W:{W}, b:{b}')
    

Epoch:0, Loss:26966.458984375, W:tensor([[2.6317],
        [2.6377],
        [2.7106]], requires_grad=True), b:tensor([0.0325], requires_grad=True)
Epoch:100, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tensor([nan], requires_grad=True)
Epoch:200, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tensor([nan], requires_grad=True)
Epoch:300, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tensor([nan], requires_grad=True)
Epoch:400, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tensor([nan], requires_grad=True)
Epoch:500, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tensor([nan], requires_grad=True)
Epoch:600, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tensor([nan], requires_grad=True)
Epoch:700, Loss:nan, W:tensor([[nan],
        [nan],
        [nan]], requires_grad=True), b:tens

nn.Module로 구현하는 선형회귀

클래스로 파이토치 모델 구현!!!!!

In [133]:
x_data
y_data


tensor([[185.],
        [180.],
        [196.],
        [142.],
        [101.],
        [149.],
        [115.],
        [175.],
        [164.],
        [141.],
        [141.],
        [184.],
        [152.],
        [148.],
        [192.],
        [147.],
        [183.],
        [177.],
        [159.],
        [177.],
        [175.],
        [175.],
        [149.],
        [192.]])

In [135]:
class LinearRegressionModel(nn.Module):
  def __inti__(self):
    super().__init__() #파이썬은 init이 생성자고, super class를 생성한다는 말???? ㅇㅁㅇ??? 부른다는 말????
    self.linear=nn.Linear(3,1)
#모델 완성

#학습할때 부르는 함수 생성
  def forward(self, x):
    return self.linear(x) #x데이터를 넣으면 이 함수를 호출함.

In [136]:
model = LinearRegressionModel()
print(list(model.parameters()))

[]


In [137]:
optimizer = optim.SGD(model.parameters(), lr=1e-6)
epochs=50001

ValueError: optimizer got an empty parameter list

In [ ]:
for epoch in range(epochs):
  y=model(x_data) #y와 b 값을 가진 model에 의해 나온 y값
  cost=F.mse_loss(y,y_data)
  optimizer.zero_grad() #for 문 돌면서 초기화

  cost.backward() #기울기 계산
  optimizer.step() #wb를 업데이트

  if epoch%100 ==0:
    print(f'epoch:{epoch}, cost:{cost.item}, w, b:{list(model.parameters())}')

In [ ]:
new_data=torch.FloatTensor([[80,90,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

In [139]:
import seaborn as sns

In [140]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [141]:
taxis=sns.load_dataset('taxis')
taxis

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]