nn.Module로구현하는선형회귀-single data 실습

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import pandas as pd

#훈련데이터

In [29]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

모델 생성

In [30]:
model=nn.Linear(1,1) # input_dim=1, output_dim=1
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


최적화

In [31]:
optimizer=optim.SGD(model.parameters(), lr=0.01)

학습

In [32]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction, t_data)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch%400==0:
      print('Epoch:', epoch, 'Cost:',cost.item())

Epoch: 0 Cost: 39.16685104370117
Epoch: 400 Cost: 0.01109258271753788
Epoch: 800 Cost: 0.0007385412463918328
Epoch: 1200 Cost: 4.91717473778408e-05
Epoch: 1600 Cost: 3.276181814726442e-06
Epoch: 2000 Cost: 2.1860606125301274e-07
Epoch: 2400 Cost: 1.4702209227834828e-08
Epoch: 2800 Cost: 9.986707016906848e-10
Epoch: 3200 Cost: 1.0809344391793374e-10
Epoch: 3600 Cost: 5.426272625674855e-11
Epoch: 4000 Cost: 5.426272625674855e-11
Epoch: 4400 Cost: 5.426272625674855e-11
Epoch: 4800 Cost: 5.426272625674855e-11
Epoch: 5200 Cost: 5.426272625674855e-11
Epoch: 5600 Cost: 5.426272625674855e-11
Epoch: 6000 Cost: 5.426272625674855e-11
Epoch: 6400 Cost: 5.426272625674855e-11
Epoch: 6800 Cost: 5.426272625674855e-11
Epoch: 7200 Cost: 5.426272625674855e-11
Epoch: 7600 Cost: 5.426272625674855e-11
Epoch: 8000 Cost: 5.426272625674855e-11
Epoch: 8400 Cost: 5.426272625674855e-11
Epoch: 8800 Cost: 5.426272625674855e-11
Epoch: 9200 Cost: 5.426272625674855e-11
Epoch: 9600 Cost: 5.426272625674855e-11
Epoch: 10

예측

In [33]:
new_data=torch.FloatTensor([[10]])
y_pred=model(new_data)
print(y_pred)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


nn.Module로 구현하는 선형 회귀- multi data 실습

실습예제1 해보자 따로

In [34]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

모델 생성

실습예제2
data/data-01-test-socre.csv
파일을 사용하여 다중 선형회귀분석을 수행해라.

In [46]:
df=pd.read_csv('../data02/data-01-test-score.csv')
df

73  80   75  152
0   93  88   93  185
1   89  91   90  180
2   96  98  100  196
3   73  66   70  142
4   53  46   55  101
5   69  74   77  149
6   47  56   60  115
7   87  79   90  175
8   79  70   88  164
9   69  70   73  141
10  70  65   74  141
11  93  95   91  184
12  79  80   73  152
13  70  73   78  148
14  93  89   96  192
15  78  75   68  147
16  81  90   93  183
17  88  92   86  177
18  78  83   77  159
19  82  86   90  177
20  86  82   89  175
21  78  83   85  175
22  76  83   71  149
23  96  93   95  192

훈련 데이터

In [36]:
x_train = torch.tensor(df.values[:,:-1], dtype=torch.float32)
y_train = torch.tensor(df.values[:,-1], dtype=torch.float32)
print("x_train:", x_train)
print("y_train:", y_train)
print("x_train.shape:", x_train.shape)
print("y_train.shape:", y_train.shape)

x_train: tensor([[ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  93.],
        [ 88.,  92.,  86.],
        [ 78.,  83.,  77.],
        [ 82.,  86.,  90.],
        [ 86.,  82.,  89.],
        [ 78.,  83.,  85.],
        [ 76.,  83.,  71.],
        [ 96.,  93.,  95.]])
y_train: tensor([185., 180., 196., 142., 101., 149., 115., 175., 164., 141., 141., 184.,
        152., 148., 192., 147., 183., 177., 159., 177., 175., 175., 149., 192.])
x_train.shape: torch.Size([24, 3])
y_train.shape: torch.Size([24])


In [37]:
# model = nn.Linear(3,1)
# print()

#자동 코드
input_dim = x_data.shape[1]
output_dim = 1

model = nn.Linear(input_dim, output_dim)
print(list(model.parameters()))

print(list(model.parameters()))는 아래의 의미
y=w1​x1​+w2​x2​+...+wn​xn​+b

Class 활용
아래의 두 데이터를 활용해서 하자.

In [45]:
print(type(x_data))

<class 'torch.Tensor'>


TypeError: expected np.ndarray (got Tensor)

class 만들기
class 이름은 내 마음대로

In [39]:
class LinearRegressionModel(nn.Module):
  def __inti__(self):
    super().__init__() #파이썬은 init이 생성자고, super class를 생성한다는 말???? ㅇㅁㅇ??? 부른다는 말????
    self.linear=nn.Linear(3,1)
#모델 완성

#학습할때 부르는 함수 생성
  def forward(self, x):
    return self.linear(x) #x데이터를 넣으면 이 함수를 호출함.
  

모델 만들기

In [40]:
model = LinearRegressionModel()
print(list(model.parameters()))

[]


In [41]:
optimizer = optim.SGD(model.parameters(), lr=0.0001)
epochs=50001

ValueError: optimizer got an empty parameter list

In [ ]:
for epoch in range(epochs):
  y=model(x_data) #y와 b 값을 가진 model에 의해 나온 y값
  cost=F.mse_loss(y-y_data)
  optimizer.zero_grad() #for 문 돌면서 초기화

  cost.backward() #기울기 계산
  optimizer.step() #wb를 업데이트

  if epoch%100 ==0:
    print(f'epoch:{epoch}, cost:{cost.item}, w, b:{model.parameters()}')
