In [84]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import metrics


In [85]:
iris = load_iris() 
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [86]:
x=iris.data
y=iris.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

타입을 보자.
넘파이 배열을 바로 쓸수가 있어.
이 데이터 자체가 150개인데 다쓰면 안되니-

In [87]:
print(type(x))
print(type(y))
print(x.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(150, 4)


훈련 - 테스트 나눴다

In [88]:
from sklearn.model_selection import train_test_split
#8:2 = train:test

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

#자르는 구간이 어떻게 선택됐나보자. 2만 쫙 있을 수 있잖아.

(120, 4) (30, 4) (120,) (30,)


In [89]:
y_test

array([2, 2, 0, 2, 1, 0, 0, 1, 0, 1, 0, 2, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0,
       1, 0, 1, 2, 2, 1, 2, 1])

0, 1, 2가 골고루 섞여있어. 원하는 비율로 고르게 섞어서 잘라줘.
우리가 데이터를 0 , 1, 2 주루루 쓸수 있으니까-
프로그램에서 섞어서 잘라줘.

In [90]:
x_test

array([[6.7, 3.3, 5.7, 2.1],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [5.4, 3. , 4.5, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.3, 3.7, 1.5, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.5, 3.9, 1.1],
       [5.5, 4.2, 1.4, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [4.9, 3.6, 1.4, 0.1],
       [6.9, 3.1, 5.4, 2.1],
       [5.8, 4. , 1.2, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [7.7, 2.8, 6.7, 2. ],
       [4.6, 3.1, 1.5, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.6, 3. , 4.5, 1.5],
       [6.4, 2.7, 5.3, 1.9],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.2, 4.1, 1.5, 0.1],
       [6.4, 2.9, 4.3, 1.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.5, 2.6, 4.4, 1.2],
       [6.5, 3. , 5.8, 2.2],
       [5.8, 2.7, 4.1, 1. ]])

숫자가 많으면 오차를 구해서 제곱을해서 다 더하면 숫자가 커져서 자원이 커짐.
이미지데이터를 다룰때, 실제 데이터의 스케일을 0과 1사이의 값을 조절해.
더해도 큰 값이 안돼.
스케일 조정을 해서 사용해!!!!!!!!!!!

데이터 준비 완료!!!
스케일 조정

In [91]:
from sklearn.preprocessing import StandardScaler

s=StandardScaler() #값의 크기를 스케일 해주는데, 평균은 0, 표준편차는 1이 됨.count

x_train1=s.fit_transform(x_train)
x_test1=s.fit_transform(x_test)
print(x_train1)
#연산이 되었을때 작은 값이 될 수 있게 해줘

[[ 1.09167053 -0.08832849  0.72908707  0.64793351]
 [-0.13838077 -1.29280784  0.72908707  1.04666182]
 [-0.2613859  -0.08832849  0.20379418  0.11629576]
 [-0.99941668  0.875255   -1.31371859 -1.34570805]
 [-1.36843208  0.39346326 -1.25535272 -1.34570805]
 [-0.99941668  0.39346326 -1.48881622 -1.34570805]
 [-1.12242181 -0.08832849 -1.37208447 -1.34570805]
 [ 0.35363975 -0.57012023  0.55398944 -0.01661368]
 [-1.12242181 -1.29280784  0.43725769  0.64793351]
 [ 0.59965001 -1.77459959  0.37889181  0.11629576]
 [-0.01537564 -0.8110161   0.78745295  0.91375238]
 [-0.38439103 -1.77459959  0.14542831  0.11629576]
 [ 2.19871671 -0.08832849  1.66294109  1.17957126]
 [-0.13838077 -0.57012023  0.20379418  0.11629576]
 [-0.87641155  0.875255   -1.31371859 -1.34570805]
 [-0.50739616  0.875255   -1.31371859 -1.07988918]
 [ 0.84566027 -0.57012023  0.49562356  0.38211463]
 [-1.61444234 -1.77459959 -1.43045035 -1.21279862]
 [ 0.59965001  0.63435913  0.55398944  0.51502407]
 [ 0.47664488  0.875255    0.96

In [92]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=10) #가장가까운 점 50개를 보고 분류함.
knn.fit(x_train1, y_train) #모델훈련을 시킴

#n_neighbors의 수치를 낮추면 정확도가 올라가
#결과는 아래처럼 나온다는데?

KNeighborsClassifier(n_neighbors=10)

In [93]:
from sklearn.metrics import accuracy_score # 정확도 측정은 사이키런안에 있어
y_pred=knn.predict(x_test1)

print(f'정확도 {accuracy_score(y_test, y_pred)}') #y_test는 정답 정확도가 0.76

정확도 0.9666666666666667


함수가지고 와서 그대로 쓰는게 중요!!!!!!!!!!!!!


In [98]:
k=50 #k를 1~10까지 줬을 때
acc_array = np.zeros(k)
for k in np.arange(1, k+1): #k가 작으면 작을 수록 정확하게 찾아. 정확도 제일 높은 값 찾기
  classifier=KNeighborsClassifier(n_neighbors=k).fit(x_train1, y_train)
  y_pred=classifier.predict(x_test1)
  acc=metrics.accuracy_score(y_test, y_pred)
  acc_array[k-1]=acc

max_acc=np.amax(acc_array)   #배열에서 가장 큰 값 찾아
acc_list = list(acc_array)
k=acc_list.index(max_acc)
print(f'정확도 {max_acc}으로 최적의 k는 {k+1}입니다')

정확도 1.0으로 최적의 k는 3입니다


In [ ]:
k=50 #k를 1~10까지 줬을 때
acc_array = np.zeros(k)
for k in np.arange(1, k+1): #k가 작으면 작을 수록 정확하게 찾아. 정확도 제일 높은 값 찾기
  classifier=KNeighborsClassifier(n_neighbors=k).fit(x_train1, y_train)
  y_pred=classifier.predict(x_test1)
  acc=metrics.accuracy_score(y_test, y_pred)
  print(k, acc) 
  #k값이 어떤 값을 가지나-, 서로 섞인 애매한 값은 k값을 너무 작게하면 못찾아.
  #k값을 적당히 주는게 좋다는데 어떻게 적당히 주지?
  acc_array[k-1]=acc

max_acc=np.amax(acc_array)   #배열에서 가장 큰 값 찾아
acc_list = list(acc_array)
k=acc_list.index(max_acc)
print(f'정확도 {max_acc}으로 최적의 k는 {k+1}입니다')

#최근접점을 보고 분류를 해. 이 값과 가장 가까운 것들을 정답으로-

1 0.9666666666666667
2 0.9333333333333333
3 1.0
4 0.9666666666666667
5 0.9666666666666667
6 0.9666666666666667
7 0.9666666666666667
8 0.9666666666666667
9 0.9666666666666667
10 0.9666666666666667
11 0.9666666666666667
12 0.9666666666666667
13 0.9666666666666667
14 0.9666666666666667
15 0.9666666666666667
16 0.9666666666666667
17 0.9666666666666667
18 0.9666666666666667
19 0.9666666666666667
20 0.9666666666666667
21 0.9666666666666667
22 0.9666666666666667
23 0.9666666666666667
24 0.9666666666666667
25 0.9666666666666667
26 0.9666666666666667
27 0.9666666666666667
28 0.9666666666666667
29 0.9666666666666667
30 0.9333333333333333
31 0.9333333333333333
32 0.9333333333333333
33 0.9333333333333333
34 0.9333333333333333
35 0.9333333333333333
36 0.9333333333333333
37 0.9333333333333333
38 0.9333333333333333
39 0.9333333333333333
40 0.9
41 0.9
42 0.9
43 0.9
44 0.9
45 0.9
46 0.9
47 0.9333333333333333
48 0.9333333333333333
49 0.9333333333333333
50 0.9
정확도 1.0으로 최적의 k는 3입니다


k-최근접이웃 끝

서포트벡터 머신부터는 내가 실습

결정트리

타이타닉 생존예측

In [100]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

타이타닉 전체 데이터 중 분석에 필요한 데이터만 추출하여 전처리

In [103]:
titanic = titanic[['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'survived']]
titanic['sex'] = titanic['sex'].map({'male':0, 'female':1 })
titanic=titanic.dropna()
x=titanic.drop('survived', axis=1)
y=titanic['survived']

C:\Users\it\AppData\Local\Temp\ipykernel_8104\1896178178.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic['sex'] = titanic['sex'].map({'male':0, 'female':1 })


# 승객의생존여부를예측하기위해'Pclass','Sex','Age','SibSp','Parch','Fare' 사용
df= df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']]
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1}) # 성별을나타내는'sex'를0또는1로변환
df= df.dropna() # 값이없는데이터삭제
X= df.drop('Survived', axis=1) # 'Survivied'를정답으로사용하기위해X에서제거
y= df['Survived'] # 'Survivied'를정답(target) 레이블로용

훈련과 테스트 데이터셋으로 분리

In [106]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=1)

In [107]:
x_test

pclass  sex   age  sibsp  parch      fare
689       1    1  15.0      0      1  211.3375
278       3    0   7.0      4      1   29.1250
506       2    1  33.0      0      2   26.0000
9         2    1  14.0      1      0   30.0708
494       3    0  21.0      0      0    8.0500
..      ...  ...   ...    ...    ...       ...
322       2    1  30.0      0      0   12.3500
597       3    0  49.0      0      0    0.0000
436       3    1  21.0      2      2   34.3750
257       1    1  30.0      0      0   86.5000
452       1    0  30.0      0      0   27.7500

[179 rows x 6 columns]

사이킷런에서 제공하는 결정트리 라이브러리 사용 모델 생성

In [108]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

모델 훈련

In [109]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

테스트 데이터셋을 이용하여 모델에 대한 예측을 진행

In [110]:
y_pred = model.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8156424581005587

예측 결과 82%로 높은 수치를 보이고 있음. 즉, 학습이 잘 되었다아~

혼동행렬

In [113]:
from sklearn.metrics import confusion_matrix
pd.DataFrame(
  confusion_matrix(y_test, y_pred),
  columns=['Predicted Not Survival', 'Predicted Survival'],
  index=['True Not Survival', 'True Survival']
)


Predicted Not Survival  Predicted Survival
True Not Survival                      97                  15
True Survival                          18                  49

이렇게 간단하게 분리할 수 있는 데이터는 잘 없어서 요즘은 잘 안쓴다!!!!
크앙 ㅜㅜㅜ